const psInternalFields = {
  "Id": "formId",
  "Filled Date Time": "filledDate",
  "Met Person Name": "metpersonName",
  "Met Person Mobile Number": "metpersonNo",
  "Year of Birth": "yearOfBirth",
  "Vaccine Name": "vaccineName",
  "State Name": "stateName",
  "District Name": "districtName",
  "Tehsil Name": "teshilName",
  "Village Name": "villageName",
  "Pincode": "pincode",
  "GPS Location": "gpsLocation",
  "Vaccination Status": "vaccinationStatus",
  "Internal Team QA": "internalTeamQA",
  "Name (from Filled By)":"Filled_By",
  "Date and Time" : "Date_and_Time",
  "House Number" : "House_Number",
  "Gender of Met Person" : "Gender_of_Met_Person",
  "Age Bracket of Met Person" : "Age_Bracket_of_Met_Person",
  "Number of Children Between 10 to 18 Age" : "Number_of_Children_Between_10_to_18_Age",
  "ID Card Type" : "ID_Card_Type",
  "ID Card Number" : "ID_Card_Number",
  "Is Vaccination Certificate Available?" : "Is_Vaccination_Certificate_Available",
  "Did you suffer from the corona?" : "Did_you_suffer_from_the_corona",
  "Date of Corona Positive Report" : "Date_of_Corona_Positive_Report",
  "Dose Status" : "Dose_Status",
  "Beneficiary ID" : "BeneficiaryID",
  "Gender" : "Gender",
  "Data Status" : "Data_Status",
  "Vaccine Dose Name" : "Vaccine_Dose_Name",
  "Vaccination Status QA" : "Vaccination_Status_QA",
  "Date of 1st Vaccination from Certificate" : "Date_of_1st_Vaccination_from_Certificate",
  "Certificate QA Done By" : "Certificate_QA_Done_By",
  "Met Person Type" : "Met_Person_Type",
  "Please Select Disability From List" : "Please_Select_Disability_From_List",
  "If other disability mention here" : "If_other_disability_mention_here",
  "Is the met person is having any Disability?" : "Is_the_met_person_is_having_any_Disability",
  "If other met person type, please mention here" : "If_other_met_person_type_please_mention_here",
  "Anaxee Executive Name" : "Anaxee_Executive_Name",
  "Id card last 4 digit number" : "Id_card_last_4_digit_number",
  "Case Status" : "Case_Status",
  "Case Assign Date" : "Case_Assign_Date",
  "OCR for 2nd Certificate Photo": "BeneficiaryReferenceID2nddose",
  "OCR Data for Vaccination Certificate":"BeneficiaryReferenceID1stDose",
};

module.exports = {
    psInternalFields,
}
