getrawfields ={
    'Id':'formId',
    'Filled Date Time':'filledDate',
    'Filled By':'filledBy',
    'Modified By':'modifiedBy',
    'Modified Time':'modifiedTime',
    '1. Select City Name from List (शहर का नाम लिस्ट मे से चुने)':'selectCityName',
    '2. District Name (जिले का नाम)':'districtName',
    '3. State Name (राज्य का नाम)':'stateName',
    '4. Pincode (पिन कोड)':'pincode',
    '5. GPS Location (जीपीएस लोकेशन)':'gpsLocation',
    '7. Shop Type (स्टोर का प्रकार)':'shopType',
    '7a. Other Shop Type':'otherShope',
    '8. Shop Name (स्टोर का नाम)':'shopName',
    '9. Shop Full Adrees (स्टोर का पूरा पता)':'shopFullAddress',
    '10. Met Person Name (स्टोर पर जो व्यक्ति मिला उसका नाम)':'metPersonName',
    '11. Met Person Number (स्टोर पर जो व्यक्ति मिला उसका मोबाइल नंबर)':'metPersonNumber',
    '12. स्टोर पर जो व्यक्ति मिला क्या वो स्टोर स्वामी है ?':'storeswami',
    '15. आपके स्टोर में Bath Towel श्रेणी में कौन से ब्रांड उपलब्ध हैं ?':'categoryOfbathTowel',
    '15a. Other Brand of bath towel (अन्य टॉवल ब्रांड का नाम )':'otherBrand',
    '16. आपके स्टोर में Bedsheet श्रेणी में कौन से ब्रांड उपलब्ध हैं ?':'bedsheetbrandinStore',
    '20. Shopkeeper is ready to place order? (क्या दुकानदार order देना चाहता है ?)':'shopkeeperIsReadytoPlaceOrder',
    '21. Total Order Value (order का कुल मूल्य)':'totalOrder',
    'Filled by Mobile Number':'filledByMobileNo',
    'Filled by Email Id':'filledbyEmailId',
    'Your Manager or Supervisor Name':'yourManagername',
    'Manager Mobile Number':'managerMobileNo',
  }
  module.exports = {
      getrawfields
  }
