getqafields = {
    "Id":'Id',
    "recID": "recID",
    "Id copy":"Id_copy",
    "DateTime of visit":"DateTime_of_visit",
    "2. जो मिला उस व्यक्ति का नंबर (Met person number)": 'Met_person_number',
    "5.  जो मिला उस व्यक्ति का लिंग (Gender of Met Person)": 'Gender_of_Met_Person',
    "4. जो मिला उस व्यक्ति की उम्र (Age of Met Person)": 'Age_of_Met_Person',
    "1. जो मिला उस व्यक्ति का नाम (Met person Name)": 'Met_person_Name',
    "गाँव का नाम (Village Name)": 'Village_Name',
    "3.  जो मिला उस व्यक्ति का प्रकार (Met Person Type)": 'Met_Person_Type',
    "8. आपके घर में कुल कितने बच्चे है (Number of Children)": 'Number_of_Children',
    "8.1 बच्चे का नाम (Name of children)": 'Name_of_children',
    "8.2 बच्चे की उम्र (Age of Child)": 'Age_of_Child',
    "Other Met Person Type (अन्य जो व्यक्ति मिला उसका प्रकार)": 'Other_Met_Person_Type',
    "6. आपके घर में कुल कितने लोग है? (Number of Family members)": 'Number_of_Family_members',
    "9. आपके गाँव में कितने स्कूल है ? (No. of schools in village)": 'No_of_schools_in_village',
    "9a. सबसे नजदीक स्कूल कितनी दुरी पर है ? (Distance of closet school)": 'Distance_of_closet_school',
    "10. बच्चे स्कूल तक कैसे जाते हैं ? (how children go to school)": 'how_children_go_to_school',
    "11. स्कूल द्वारा आपको क्या क्या सुविधाएं दी गई हैं ? (What are the facilities provided to you by the school)": 'What_are_the_facilities_provided_to_you_by_the_school',
    "11a. यदि अन्य कृपया उल्लेख करें ( if others please mention)": 'if_others_please_mention',
    "12. कोरोना काल के बाद सर्व शिक्षा अभियान के तहत क्या टीचर आपके घर आए थे क्या दाखिला कराने के लिए ?": 'AftrCorona_teachers_cometohouse_under_SarvaShikshaAbhiyan',
    "13. कोई टिप्पणी (Any Remark)": 'Any_Remark',
    "राज्य का नाम (State Name)": 'State_Name',
    "जिले का नाम (District Name)": 'District_Name',
    "तहसील का नाम (Taluka Name)": 'Taluka_Name',
    "Pincode": 'Pincode',
    "GPS Location": 'GPS_Location',
    "8.3 बच्चे का लिंग (Gender of the child)": 'Gender_of_the_child',
    "8.4 बच्चे ने कोरोनाकाल के 2 साल में क्या किया ? (What did the child do in 2 years of Corona)": 'What_did_the_child_do_in_2_years_of_Corona',
    "8.4a अगर ऑनलाइन क्लास की है, तो कैसे की है ? (f there is an online class, how is it done)": 'If_there_is_an_online_class_how_is_it_done',
    "8.4c आपको इंटरनेट की सुविधा कैसे मिलती थी ? ( How did you get internet access)": 'How_did_you_get_internet_access',
    "8.5 कोरोना के पहले कौन सी क्लास मे थे ? (In which class were you before Corona)": 'In_which_class_were_you_before_Corona',
    "8.6 कोरोना के बाद कौन सी क्लास मे हैं ? (In which class are you after Corona)": 'In_which_class_are_you_after_Corona',
    "8.6a. बच्चे ने पढाई क्यू छोड़ दी है ? (Why has the child left studies)": 'Why_has_the_child_left_studies',
    "8.6a1 पढ़ाई छोड़ने का अन्य कारण (Other reasons for dropping out)": 'Other_reasons_for_dropping_out',
    "8.6b स्कूल का पूरा नाम और पता ()Full name and address of the school": 'Full_name_and_address_of_the_school',
    "8.6c स्कूल का प्रकार? (Type of school)": 'Type_of_school',
    "8.7 आपके बच्चे को पढ़ाई संबन्धित कोई समस्या है क्या ? (Does your child have any academic problems)": 'Does_your_child_have_any_academic_problems',
    "8.8 आपके बच्चे को पढ़ाई संबन्धित कोई मदद चाहिए क्या ? (Does your child need any academic help)": 'Does_your_child_need_any_academic_help',
    "Filled By": 'Filled_By',
    "Filled Time": 'Filled_Time',
    "Modified By": 'Modified_By',
    "Modified Time": 'Modified_Time',
    "QA Remark": 'QA_Remark',
    "QA Done By": 'QA_Done_By',
    "QA Call Status": 'QA_Call_Status',
    "QA Status": 'QA_Status',
    "Rejection Reason": 'Rejection_Reason',
    "QA Done Date": 'QA_Done_Date'

}


module.exports = {
    getqafields
}