const getMahindraEscortTsLeadQaFields = {
  "Id": "Id",
  "Met Person Mobile Number (जो व्यक्ति मिला उसका मोबाइल नंबर )": 'Met_Person_Mobile_Number',
  "Filled Date": 'Filled_Date',
  "Modified Date": 'Modified_Date',
  "Gender of Met Person (जो व्यक्ति मिला उसका लिंग)": "Gender_of_Met_Person",
  "Met Person Type? (जो व्यक्ति मिला उसका प्रकार)": 'Met_Person_Type',
  "Age Bracket of Met Person (जो व्यक्ति मिला उसकी उम्र)": 'Age_Bracket_of_Met_Person',
  "G2. Do you want to purchase Tractor? (क्या आप ट्रैक्टर खरीदना चाहते है)": 'Do_you_want_to_purchase_Tractor',
  "G2. When you will purchase tractor? (आप ट्रैक्टर कितने दिनो मे खरीदने वालों हो)": 'When_you_will_purchase_tractor',
  "G2. Ask 3 Brands of Tractor for purchase,  कोई 3 या ज्यादा कंपनी का नाम पूछे जिसे किसान खरीदना चाहते": 'Ask_3_Brands_of_Tractor_for_purchase',
  "G2. How many HP Tractor you want? (आपको कितने एचपी का ट्रैक्टर लेना है?)": 'How_many_HP_Tractor_you_want',
  "T1.Are you interested in buying Mahindra Tractors?(क्या आप महिंद्रा ट्रैक्टर खरीदने में रुचि रखते हैं?)": 'Are_you_interested_in_buying_Mahindra_Tractors',
  "T2.Are you interested in buying Escorts-Farmtrac Tractors?(क्या आप एस्कॉर्ट्स-फार्मट्रैक ट्रैक्टर खरीदने में रुचि रखते हैं?)": 'Are_you_interested_in_buying_Escorts_Farmtrac_Tractors',
  "G2. From where you will buy tractor? (आप ट्रैक्टर कहाँ से खरीदने वालों हो? )": 'From_where_you_will_buy_tractor',
  "G2. Will Purchase Tractor in Cash or other method? (आप ट्रैक्टर कैसे खरीदेंगे?)": 'Will_Purchase_Tractor_in_Cash_or_other_method',
  "G2. What is Usage for tractor? (आप ट्रैक्टर कौन कौन से कार्य के उपयोग के लिए करते हो?)": 'What_is_Usage_for_tractor',
  "G3. Planning to buy any implements or products? (क्या आपको कोई उपकरण खरीदना है?": 'Planning_to_buy_any_implements_or_products',
  "G1.Do you have any Tractors?(क्या आपके पास ट्रैक्टर है?)": 'Do_you_have_any_Tractors',
  "G1.Which Brand Tractor(s) do you own? (आपके पास कौन कौन सी कंपनी का ट्रेक्टर है)": 'Which_Brand_Tractors_do_you_own',
  "G1. How much Tractor HP you have?(आपके पास कितने एचपी का ट्रेक्टर है)": 'How_much_Tractor_HP_you_have',
  "G1.Select the model number of tractor (ट्रैक्टर कोनसे model का है ?। लिस्ट से चुने)": 'Select_the_model_number_of_tractor',
  "G1. Tractor Purchased Year (आपने ट्रेक्टर कौन से साल मे खरीदा था)": 'Tractor_Purchased_Year',
  "G1. Tractor Physically Available? (क्या ट्रेक्टर अभी के समय आपके साथ है?)": 'Tractor_Physically_Available',
  "G3. What are implements availble with you? (आपके पास कौन कौन से उपकरण है?)": 'What_are_implements_availble_with_you',
  "G3. Do you take or give Tractor and implements on rent? (क्या आप ट्रेक्टर किराए पर लेते-देते है?)": 'Do_you_take_or_give_Tractor_and_implements_on_rent',
  "Did you choose the villages name on Anaxee Portal? (क्या आपने Anaxee Portal पर गाँवो के नाम चुने है?)": 'Did_you_choose_the_villages_name_on_Anaxee_Portal',
  "State Name (राज्य का नाम)": 'State_Name',
  "District Name (जिले का नाम)": 'District_Name',
  "Tehsil Name (तहसील का नाम)": 'Tehsil_Name',
  "Village Name (गाँव का नाम)": 'Village_Name',
  "Select Village Name by Village Id": 'Select_Village_Name_by_Village_Id',
  "Pincode (पिन कोड)": 'Pincode',
  "GPS Location (जीपीएस लोकेशन)": 'GPS_Location',
  "Do you own a smartphone? (क्या आपके पास स्मार्ट फोन या टच स्क्रीन वाला फोन है?)": 'Do_you_own_a_smartphone',
  "G4. Do you want to sell tractor? (क्या आपको ट्रैक्टर बेचना है ?)": 'Do_you_want_to_sell_tractor',
  "Your Manager or Supervisor Name": 'Your_Manager_or_Supervisor_Name',
  "QA Done By": 'QA_Done_By',
  "QA Call Status": 'QA_Call_Status',
  "Rejection Reason": 'Rejection_Reason',
  "QA Lead Status": 'QA_Lead_Status',
  "Filled by Mobile Number": 'Filled_by_Mobile_Number',
  "Filled by Email Id": 'Filled_by_Email_Id',
  "Customer QA Status": 'Customer_QA_Status',
  "Interested in Escorts": 'Interested_in_Escorts',
  "Lead Type": 'Lead_Type',
  "When will you purchase in days": 'When_will_you_purchase_in_days',
  "QA Done Date": 'QA_Done_Date',
  "Filled By": 'Filled_By',
  "Filled Time": 'Filled_Time',
  "P1P2 Filled By": 'P1P2_Filled_By',
  "P1P2 Status": 'P1P2_Status',
  "Date and Time of Visit": 'Date_and_Time_of_Visit',
  "Met Person Name (जो व्यक्ति मिला उसका नाम)": 'Met_Person_Name',
  "Met Person Whatsapp-Alternate No.|जो मिला उसका WhatsApp No.या घर पर जिसके पास smartphone हो उसका No.": 'Met_Person_Whatsapp_Alternate_No',
  "Tractor Owner or Buyer Full Address (जो व्यक्ति मिला उसका पूरा पता लिखे) - New Lead": 'Tractor_Owner_or_Buyer_Full_Address',
  "If Other Village then Mention Here (यदि अन्य गाँव है तो यहा लिखे)": 'If_Other_Village_then_Mention_Here',
  "G2. If Others usage, Please Mention here (यदि अन्य है तो यहाँ लिखे)": 'If_Others_usage_Please_Mention_here',
  "G3. If Others implements, Please Mention here (यदि अन्य है तो यहाँ लिखे)": 'If_Others_implements_Please_Mention_here',
  "G4. Condition of Tractor?": 'Condition_of_Tractor',
  "Your Anaxee Support Name": 'Your_Anaxee_Support_Name',
  "Modified By": 'Modified_By',
  "Modified Time": 'Modified_Time',
  "QA Call Attempt": 'QA_Call_Attempt',
  "QA Remark": 'QA_Remark',
  "Customer QA Status": 'Customer_QA_Status',
  "Tractor with Met Person Photo Check QA": 'Tractor_with_Met_Person_Photo_Check_QA',
  "Only Met Person Photo Check QA": 'Only_Met_Person_Photo_Check_QA',
  "QA Done Date(Don't Use)": 'QADone_Date_Dont_Use',
  "Manager Mobile Number": 'Manager_Mobile_Number',
  "Expected Date of Purchase": 'Expected_Date_of_Purchase',
  "Number of days to Purchase": 'Number_of_days_to_Purchase',
  "Upload To Customer Base": 'Upload_To_Customer_Base',
  "Report Sent Date": 'Report_Sent_Date',
  "Payment Status": 'Payment_Status',
  "Payment Process Date": 'Payment_Process_Date',
  "Email Sent": 'Email_Sent',
  "Created Time": 'Created_Time',
  "Did you take any details from dealer/Showroom about the tractor (क्या आपने डीलर से ट्रैक्टर के बारे में कोई जानकारी ली हे?": 'Did_u_tk_details_from_dealerShowroom_abt_tractor',
  "If Yes, Mention the Dealer or Agency Name (अगर हा, डीलर या एजन्सि का नाम बताए)": 'If_Yes_Mention_the_Dealer_or_Agency_Name',
  "Do you have a smartphone? (क्या आपके पास स्मार्ट फोन या टच स्क्रीन वाला फोन है?)": 'Do_you_have_a_smartphone',
  "Did the Met Person Allowed for Data? (क्या जो व्यक्ति मिला, उसने अनुमति दी है?": 'Did_the_Met_Person_Allowed_for_Data',
  "G1. Are you satisfied with your tractor? (क्या आप अपने ट्रैक्टर से संतुष्ट हैं?)": 'Are_you_satisfied_with_your_tractor',
  "If no then why? (आप संतुष्ट क्यों नहीं है?)": 'If_no_then_why',
  "Anaxee Leads Converted in TO?": "Anaxee_Leads_Converted_in_TO",
  "G1. Mention Tractor Number from Number Plate (नंबर प्लेट से ट्रैक्टर का नंबर लिखे)": "Mention_Tractor_Number_from_Number_Plate",
  "Hot Lead Shared with Runner": "Hot_Lead_Shared_with_Runner",
  "Priority District": "Priority_District",
  "Focus Brand": "Focus_Brand",
};

module.exports = {
  getMahindraEscortTsLeadQaFields,
};
