const getFields = {
  beneficiary_reference_id: "beneficiary_reference_id",
  name: "name",
  mobile_number: "mobile_number",
  birth_year: "birth_year",
  gender: "gender",
  photo_id_type: "photo_id_type",
  photo_id_number: "photo_id_number",
  type_of_person: "type_of_person",
  comorbidity_ind: "comorbidity_ind",
  vaccination_status: "vaccination_status",
  vaccine: "vaccine",
  dose1_date: "dose1_date",
  dose2_date: "dose2_date",
  state: "state",
  district: "district",
  taluka: "taluka",
  village: "village",
  pincode: "pincode",
  tested_postiive_for_corona: "tested_postiive_for_corona",
  corona_test_date: "corona_test_date",
  is_any_disability: "is_any_disability",
  disability_type: "disability_type",
  need_assistance: "need_assistance",
  assistance_type: "assistance_type",
  other_assistance_type: "other_assistance_type",
  pwd_certificate_available: "pwd_certificate_available",
  pwd_certificate_link: "pwd_certificate_link",
  lat_lng: "lat_lng",
  register_user_type: "register_user_type",
  register_user_id: "register_user_id",
  register_mobile_number: "register_mobile_number",
  register_user_email: "register_user_email",
  registration_response: "registration_response",
  session_token: "session_token",
  registration_time: "created_at",
  runner_mobile: "runner_mobile",
  runner_email: "runner_email",
  submit_status: "submit_status",
  api: "api",
  api_response: "api_response",
  date_time: "date_time",
  gps: "gps",
  err_code_and_msg: "err_code_and_msg",
  beneficiary_mobile_number: "beneficiary_mobile_number",
  beneficiary_Id_from_2nd_dose: "beneficiary_reference_id_copy",
  registration_name: "name_copy",
  mobile_number_copy: "mobile_number_copy",
  birth_year_copy: "birth_year_copy",
  gender_copy: "gender_copy",
  photo_id_type_copy: "photo_id_type_copy",
  photo_id_number_copy: "photo_id_number_copy",
  vaccination_status_copy: "vaccination_status_copy",
  vaccine_copy: "vaccine_copy",
  dose1_date_copy: "dose1_date_copy",
  runner_name: "runner_name",
  managers_mobile_number: "managers_mobile_number",
  app_version: "app_version"
};

module.exports = {
  getFields,
};
